package se.ju14.scrumboard.repository;

import java.util.List;

import se.ju14.scrumboard.model.Member;
import se.ju14.scrumboard.model.status.MemberStatus;
import se.ju14.scrumboard.repository.action.MemberRepository;

/**
 * 
 * @author Pierre Vanderpol, Jesper Wendler, Erik Perez
 *
 */
public final class JpaMemberRepository extends InMemoryRepository<Member> implements MemberRepository {

	
	/**
	 * Creates a new Member object in the database and gives it an ID
	 * 
	 * @parameter Entity : a valid Entity parameter is needed
	 * @return returns a newly created Member object
	 */
	@Override
	public Member create(Member entity) {
		super.saveOrUpdateEntity(manager ->{
			entity.setMemberId(AUTOGENERATED_ID);
			manager.persist(entity);
		});
		
		return entity;
	}

	/**
	 * Updates an existing User object in the database(?)
	 * 
	 * @parameter User : a valid User parameter is needed
	 * @return returns the updated User object
	 */
	@Override
	public Member update(Member entity) {
		super.saveOrUpdateEntity(manager ->{
			manager.merge(entity);
		});
		return entity;

	}

	/**
	 * Deletes an existing User object in the database. Objects are never
	 * deleted but their status is changed.
	 * 
	 * @parameter User : a valid User parameter is needed
	 * @return returns the updated User object
	 */
	@Override
	public Member delete(Member entity) {
		super.saveOrUpdateEntity(manager ->{
			entity.setMemberStatus(MemberStatus.DELETED);
			manager.merge(entity);
		});
		return entity;		
	}
	
	@Override
	public List<Member> getAll() {
		return super.executeQuery("Member.findAll", Member.class);
	}

	@Override
	public Member getMemberById(String memberId) {
		return super.executeQuery("Member.findById", Member.class, "memberId", memberId).get(0);
	}

	@Override
	public List<Member> getMemberByFirstName(String firstName) {
		// TODO Auto-generated method stub
		return super.executeQuery("Member.findByFirstName", Member.class, "firstName", firstName);
	}

	@Override
	public List<Member> getMemberByLastName(String lastName) {
		return super.executeQuery("Member.findByLastName", Member.class, "lastName", lastName);
	}

	@Override
	public Member getMemberByUserName(String userName) {
		// TODO Auto-generated method stub
		return super.executeQuery("Member.findByUserName", Member.class, "userName", userName).get(0);
	}
	
}
